FROM node:lts-alpine AS build

RUN addgroup app && adduser -S -G app app

WORKDIR /app

COPY package*.json .

RUN npm install

COPY .env . 

COPY . .

RUN chown -R app:app /app

USER app

EXPOSE 5173

ENV NODE_ENV=production

RUN ["npm", "run", "build"]


FROM nginxinc/nginx-unprivileged:alpine3.22-perl AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]