FROM node:lts-alpine AS build

RUN addgroup app && adduser -S -G app app

WORKDIR /app

COPY package*.json .

RUN npm install

RUN chown -R app:app /app

USER app

EXPOSE 5173

ENV NODE_ENV=development